Task3
galexal/DirectumLab-2021-Galushko_AA pull request #2
Opened 2021-03-03 15:54 UTC by galexal

2021-03-04 06:32 UTC, LikhvarDS commented
Давай я проверю после того как замерджим PR по 2 заданию.

2021-03-04 09:39 UTC, LikhvarDS commented
После мерджа PR в мастер, этот PR сам не распознал, что там в мастере уже есть некоторые изменения, которые попали сюда. Чтобы это поправить можно подливать мастер в ветку ПулРеквеста.
Если создавать ветку с мастера, то такой проблемы больше появиться не должно

2021-03-04 09:50 UTC, LikhvarDS commented
В репозиторий попал кэш стайл копа. В коммите, в которым ты его запушил, ты писал, что некоторые файлы проигнорировались и поэтому убрал красную метку. Если такое будет ещё - лучше созвониться и разобраться.

2021-03-04 09:54 UTC, galexal commented
Я убрал метки только с .cs файлов.

2021-03-04 10:07 UTC, LikhvarDS requested changes

2021-03-04 10:07 UTC, LikhvarDS commented on dotNet module/Task3/Round.cs
> +        public virtual double Area() => Math.PI * this.OuterRadius * this.OuterRadius;
Сделать свойством, а не методом (убрать скобки)

2021-03-04 10:07 UTC, LikhvarDS commented on dotNet module/Task3/Round.cs
>          public Round() { }
Давай уберём конструкторы без параметров. Тут и в других классах они не нужны.

2021-03-04 10:07 UTC, LikhvarDS commented on dotNet module/Task3/Square.cs
> +        public int SideA_Length { get; set; }
Можно назвать просто Side

2021-03-04 10:07 UTC, LikhvarDS commented on dotNet module/Task3/Round.cs
> +        public virtual double Area() => Math.PI * this.OuterRadius * this.OuterRadius;
в других классах тоже

2021-03-04 10:07 UTC, LikhvarDS commented on dotNet module/Task3/Square.cs
> +        public int SideA_Length { get; set; }
А. Ты таким образом сделал наследование.
Это то, о чём я говорил. В некоторых случаях этот вариант имеет место быть.
В таком случае можно просто убрать _Length.

2021-03-05 04:18 UTC, LikhvarDS requested changes
Наверное, по этому вопросу лучше созвониться.

2021-03-05 04:18 UTC, LikhvarDS commented on dotNet module/Task3/StyleCop.Cache
> +</stylecopresultscache>
Ну вот здесь же ты наоборот добавил файл.

2021-03-05 04:18 UTC, LikhvarDS commented on dotNet module/Task3/Task3.csproj
> +
Здесь ты исключил его из проекта - то есть он теперь не будет показываться в проекте в студии, что в обще не важно.
Но это не влияет на то, попадает ли он в репозиторий или нет.

2021-03-05 05:06 UTC, galexal commented
Удалил StyleCop.Cashe из локальной папки, запушил. Сейчас его нет на гите в третьей ветке. В новой четвертой ветке тоже нет. Так норм? Или все-таки созвонимся?

2021-03-05 07:50 UTC, LikhvarDS approved these changes
Принято

2021-03-05 11:12 UTC, merged